# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 22:43
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('sex', models.CharField(blank=True, choices=[(None, '-----'), ('1', 'Male'), ('2', 'Female')], max_length=2, verbose_name='Sex')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Client address')),
                ('contact_info', models.TextField(verbose_name='Client contact information')),
                ('user_photo', models.ImageField(blank=True, upload_to='pilots/', verbose_name='Client profile image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('data', models.TextField(verbose_name='Data')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Creating date')),
                ('delivered', models.BooleanField(default=False, verbose_name='Is delivered?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmarket.ClientProfile', verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'verbose_name': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Order title')),
                ('url', models.SlugField(max_length=256, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Main description')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('sensor_type', models.CharField(blank=True, help_text='RGB, NGB, NRB, lidar, etc', max_length=100, verbose_name='Sensor type')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Client address')),
                ('shape_on_map', models.CharField(max_length=100, verbose_name='Shape on map')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Creating date')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Finish date')),
                ('category', models.ManyToManyField(blank=True, related_name='category_orders', to='webmarket.Category', verbose_name='Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='webmarket.ClientProfile', verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ('title',),
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=256, verbose_name='URL')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('sex', models.CharField(blank=True, choices=[(None, '-----'), ('1', 'Male'), ('2', 'Female')], max_length=2, verbose_name='Sex')),
                ('user_photo', models.ImageField(blank=True, upload_to='pilots/', verbose_name='Pilot profile image')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Pilot address')),
                ('contact_info', models.TextField(verbose_name='Pilot contact information')),
                ('description', models.TextField(blank=True, verbose_name='Main description')),
                ('area', models.CharField(blank=True, max_length=256, verbose_name='Area of responsibility')),
                ('scout_type', models.CharField(blank=True, choices=[(None, '-----'), ('Video', 'Video'), ('Photo', 'Photo'), ('LIDAR', 'LIDAR')], max_length=10, verbose_name='Scouting type')),
                ('drone_model', models.CharField(blank=True, max_length=100, verbose_name='Drone model')),
                ('drone_type', models.CharField(blank=True, choices=[(None, '-----'), ('Plane', 'Plane'), ('Copter', 'Copter')], max_length=10, verbose_name='Drone type')),
                ('sensor_type', models.CharField(blank=True, help_text='RGB, NGB, NRB, lidar, etc', max_length=256, verbose_name='Sensor type')),
                ('price', models.CharField(blank=True, help_text='price per Ha/Hour, Min Order', max_length=256, verbose_name='Pricing')),
                ('rating', models.FloatField(editable=False, null=True, verbose_name='Rating')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('category', models.ManyToManyField(blank=True, related_name='pilots', to='webmarket.Category', verbose_name='Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Pilots',
                'verbose_name': 'Pilot',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_orders', to='webmarket.PilotProfile', verbose_name='Pilot'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmarket.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmarket.PilotProfile', verbose_name='Pilot'),
        ),
    ]
